name: Build LaTeX PDF (with Artifacts)

on:
  push:
    branches:
      - main
    paths:
      - 'thesis/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: thesis
          root_file: main.tex

      # - name: Commit PDF
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Automated: Rebuild PDF"
      #     file_pattern: "thesis/main.pdf"

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Output
          path: thesis/main.pdf
